#                             NUMPY COMPLETE NOTES

## CH01 INTRODUCTION

In [ ]:
intro="""
1. numpy is a python library. NumPy was created in 2005 by Travis Oliphant 
2. numpy stands for numerical python 
3. numpy is open source (free)
4. universal standard for working with numerical data in Python
5. The NumPy API is used extensively in Pandas, SciPy, Matplotlib, scikit-learn, scikit-image and most other data science 
   and scientific Python packages.
   
   Data Science: is a branch of computer science where we study how to store, 
   use and analyze data for deriving information from it.
   
"""

In [11]:
"""
6. NumPy aims to provide an array object that is up to 50x more faster than traditional Python lists.(see demo below)
"""

import numpy as np 

numbers=np.random.rand(10000000) #generate random numbers 

%timeit sum(numbers)  #python sum function 

%timeit np.sum(numbers) #numpy sum functions 

#defining a user defined function to add sum of random numbers and check calculation speed 

def mysum(num):
    total=0
    for i in num:
        total+=i
    return total
#now calling the function mysum 
%timeit mysum(numbers)

511 ms ± 6.57 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
7.86 ms ± 34.8 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
601 ms ± 3.91 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [13]:
"""
 NumPy, array data is stored in a continuous block of memory. This is a key feature that contributes to the efficiency 
 and speed of NumPy operations.

The ndarray object in NumPy represents a multidimensional, homogeneous array of fixed-size items. 
The elements in the array are stored in a contiguous block of memory, and the information about the shape, 
data type, and strides is stored in a separate data structure. 
The contiguous memory layout allows for efficient access and manipulation of array elements.
"""


import numpy as np

# Creating a NumPy array
arr = np.array([[21,22,25,67],
                [34,35,65,66],
                [22,24,67,45]])

# Checking the memory layout
#flags['C_CONTIGUOUS'] attribute checks whether the array is stored in C-style contiguous memory
print(arr.flags['C_CONTIGUOUS']) 

True


In [16]:
"""
The array object in NumPy is called ndarray
Arrays are very frequently used in data science, where speed and resources are very important.
"""
import numpy as np 
l1=[12,14,15,67,55]
print("the l1 data type is = ",type(list1))
arr=np.array(list1)
print("the arr data type is = ",type(arr))


the l1 data type is =  <class 'list'>
the arr data type is =  <class 'numpy.ndarray'>


In [ ]:
"""
The source code for NumPy is located at this github repository https://github.com/numpy/numpy
github: enables many people to work on the same codebase

If you already have Python, you can install NumPy with:

conda install numpy
or

pip install numpy

"""

In [17]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [21]:
"""
to check version of numpy package
"""
import numpy as np

print(np.__version__)

1.26.1


##  CH02 NUMPY BASICS 

In [ ]:
"""
in this chaper cover basic of scalar(single quantity),vector(1d array),matrix(2d array) and 
covers 3d array (matrix of matrixes), 
nd array, and conversion 1d to 2d array and vice versa 
ndarray.ndim, ndarray.size, ndarray.shape
np.array(), np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace(), dtype (data types)

"""

In [6]:
#scalar it has signle quantity has no dimensions (dimension =0)

import numpy as np 

a=20
arr=np.array(a)
#printing a value 
print(a)
print(type(a))
#printing arr value 
print(arr)
print(type(arr))
print(arr.ndim) #print the dimension of numpy array 
print(arr.shape) #print the shape of array (row,columns) in tuple format
print(arr.size) # print total number of elements present in array 


20
<class 'int'>
20
<class 'numpy.ndarray'>
0
()
1


In [7]:
#vector it has signle direction has one dimension (dimension =1) either row or columns vectors
#in numpy it is neither a row vector nor a column vector by default. It is just a one-dimensional array.
#its dimension is 1

import numpy as np 

a=[12,15,34,67,32,85]
arr=np.array(a)
#printing a value 
print(a)
print(type(a))
#printing arr value 
print(arr)
print(type(arr))
print(arr.ndim) #print the dimension of numpy array 
print(arr.shape) #print the shape of array (row,columns) in tuple format
print(arr.size) # print total number of elements present in array 

[12, 15, 34, 67, 32, 85]
<class 'list'>
[12 15 34 67 32 85]
<class 'numpy.ndarray'>
1
(6,)
6


In [9]:
#However, if you want to explicitly convert it to a row or column vector, you can use the reshape method. For example:
#now its dimension will be 2 
import numpy as np

a = [12, 15, 34, 67, 32, 85]
print("Original array:")
print(arr)

#convert to np array
arr = np.array(a)

# Convert to a row vector
row_vector = arr.reshape(1, -1)
print("\nRow vector:")
print(row_vector)
print(type(row_vector))
print(row_vector.ndim) #print the dimension of numpy array 
print(row_vector.shape) #print the shape of array (row,columns) in tuple format
print(row_vector.size) # print total number of elements present in array 

# Convert to a column vector
column_vector = arr.reshape(-1, 1)
print("\nColumn vector:")
print(column_vector)
print(type(column_vector))
print(column_vector.ndim) #print the dimension of numpy array 
print(column_vector.shape) #print the shape of array (row,columns) in tuple format
print(column_vector.size) # print total number of elements present in array 





Original array:
[12 15 34 67 32 85]

Row vector:
[[12 15 34 67 32 85]]
<class 'numpy.ndarray'>
2
(1, 6)
6

Column vector:
[[12]
 [15]
 [34]
 [67]
 [32]
 [85]]
<class 'numpy.ndarray'>
2
(6, 1)
6


In [20]:
#matrix it has two direction called row and columns vectors, it has dimension 2
#in numpy it is neither a row vector nor a column vector by default. It is just a one-dimensional array.
#its dimension is 2 it has both rows and colums more than 1 
#note if row =1 columns more than one than it will be colummn matrix (1X6) in previous example
#note if row =morethan one  columns =1 than it will be colummn matrix (6X1) in previous example 

#2d matrix 

import numpy as np

# Using np.array with a list of lists
matrix = np.array([
                    [1, 2, 3],
                    [4, 5, 6], 
                    [7, 8, 9]
                ])

print(matrix)


print("\n\nprinting another matrix\n\n ")
# Using np.array with a list of lists
matrix = np.array([[31, 23, 43], [94, 55, 86], [77, 88, 91],[34,65,78]])

print(matrix)
print("\nthe type of matix is =",type(matrix).__name__)
print("the matrix dimension is = ",matrix.ndim) #print the dimension of numpy array 
print("matrix shape in tuple = ",matrix.shape) #print the shape of array (row,columns) in tuple format
print("elements present in matrix is = ",matrix.size) # print total number of elements present in array 

print("printing matrix row and columns values ")
print("row = ",matrix.shape[0])
print("col = ",matrix.shape[1])


[[1 2 3]
 [4 5 6]
 [7 8 9]]


printing another matrix

 
[[31 23 43]
 [94 55 86]
 [77 88 91]
 [34 65 78]]

the type of matix is = ndarray
the matrix dimension is =  2
matrix shape in tuple =  (4, 3)
elements present in matrix is =  12
printing matrix row and columns values 
row =  4
col =  3


In [24]:
#creating 3 dimension using np.zeros()
import numpy as np

# Creating a 3-dimensional matrix filled with zeros
shape = (3, 3, 4)  # Specify the size of each dimension
matrix = np.zeros(shape)

print(matrix)
print("\nthe type of matix is =",type(matrix).__name__)
print("the matrix dimension is = ",matrix.ndim) #print the dimension of numpy array 
print("matrix shape in tuple = ",matrix.shape) #print the shape of array (row,columns) in tuple format
print("elements present in matrix is = ",matrix.size) # print total number of elements present in array 



[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]

the type of matix is = ndarray
the matrix dimension is =  3
matrix shape in tuple =  (3, 3, 4)
elements present in matrix is =  36


## matrix creation np.array(), np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace()

In [25]:
#create 3X3 matrix with np.array()
import numpy as np 

matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [28]:
#create 3X3 matrix with np.zeros() it will give all the elements zero
#shapes should give in tuple format

import numpy as np 
#ex1
matrix=np.zeros((3,3))
print(matrix)
print("\n\n")
#ex2
shape=(4,3)
mat=np.zeros(shape)
print(mat)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]



[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [29]:
#create 3X3 matrix with np.ones() it will give all the elements one
#shapes should give in tuple format

import numpy as np 
#ex1
matrix=np.ones((3,3))
print(matrix)
print("\n\n")
#ex2
shape=(4,3)
mat=np.ones(shape)
print(mat)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]



[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [51]:
#creating a 5 dimension array 
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [34]:
# Creating an empty array with shape (2, 3)
#it will contains some garbage values 
import numpy as np

# Creating an empty array with shape (2, 3)
empty_array = np.empty((2, 3))

print(empty_array)


[[4.88059032e-313 1.99467604e-312 1.82491638e-312]
 [1.86735630e-312 7.21478569e-313 1.65515672e-312]]


In [36]:
#another way to create 
#order: Specifies whether to store the array in C-style (row-major) or Fortran-style (column-major) order. Optional, 
#and if not specified, it defaults to 'C'.
#
#
import numpy 
shape=(5,4)
temp=numpy.empty(shape, dtype=float, order='C')
print(temp)

[[1.33001884e-311 6.27463370e-322 0.00000000e+000 0.00000000e+000]
 [7.56587583e-307 1.16096346e-028 9.82205649e+252 1.11789342e+253]
 [1.29453371e-153 9.11160086e+130 4.10115249e+223 1.19684762e+141]
 [6.96770842e+252 7.20123395e+252 2.17436711e+243 2.66006218e-061]
 [9.14747031e+140 8.45888278e-053 1.81152937e-152 1.56189128e-033]]


In [43]:
#create arrays with np.arange(start:end:step) 
#end ends with n-1 ex: in this code end =11, but it stops at 10
#step is default is 1. if you want we can change step 
import numpy as np

arange_array=np.arange(1,11)
print(arange_array)

arange_array=np.arange(11)
print(arange_array)

arange_array=np.arange(11,22)
print(arange_array)

arange_array=np.arange(11,22,2)
print(arange_array)

arange_array=np.arange(11,22,3)
print(arange_array)

[ 1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20 21]
[11 13 15 17 19 21]
[11 14 17 20]


In [48]:
#reshape the np.range() values 
arange_array=np.arange(1,11)
print(arange_array)


[ 1  2  3  4  5  6  7  8  9 10]


In [49]:
arange_array=np.arange(1,11).reshape((2,5))
print(arange_array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [50]:
arange_array=np.arange(1,11).reshape((5,2))
print(arange_array)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
